FIND_PACKAGE(Boost COMPONENTS filesystem system unit_test_framework REQUIRED)

ADD_DEFINITIONS(-DBOOST_TEST_DYN_LINK)

ADD_EXECUTABLE(CheckODE
  test_main.cpp
  test_RKCK.cpp
  test_DOPRI5.cpp)

TARGET_INCLUDE_DIRECTORIES(CheckODE PRIVATE ${CMAKE_SOURCE_DIR})

TARGET_LINK_LIBRARIES(CheckODE
  ${Boost_UNIT_TEST_FRAMEWORK_LIBRARY})

SET_TARGET_PROPERTIES(CheckODE PROPERTIES
  RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/")
